mantisbt:
  image: xlrl/mantisbt:latest
  environment:
    XDEBUG_CONFIG: remote_host={{192.168.0.202}}
  ports:
    - "8989:80"
  links:
    - mysql
  restart: always
  volumes:
    - /srv/mantis/config:/var/www/html/config
    - /srv/mantis/custom:/var/www/html/custom

mysql:
  image: mariadb:latest
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=bugtracker
    - MYSQL_USER=mantis
    - MYSQL_PASSWORD=mantis
  restart: always
  volumes:
    - /srv/mantis/mysql:/var/lib/mysql

postgres:
  image: postgres:latest
  environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=root
  restart: always
